### ISSUE TITLE
Star Spawn for Eyerok was had incorrect coordinates

### ISSUE THREAD

**Issue by 64BitMouse** [64BitMouse/Project-Reimagined-Co-op-Edition-#2]
Eyerok's star had spawned out of bounds when he was defeated.

Bug found by JaydenSM64

Once this issue has been closed, please go to

levels > level_ssl_entry.lvl

and download that file to keep from constantly redownloading the entire mod.

**Comment by Zeta64Speedruns** [comment]
I still seem to be having this issue

**Comment by Zeta64Speedruns** [comment]
Yep, double checked lol
