### ISSUE TITLE
Can't open the mod

### ISSUE THREAD

**Issue by Stiqu** [64BitMouse/Project-Reimagined-Co-op-Edition-#9]
Whenever I try to boot up the mod it freezes and comes up with an error that says "Pointer not found: RM_Scroll_Texture"
Don't have much more information, thank you for your help.

**Comment by 64BitMouse** [comment]
I'm pretty sure it's because you're not up to date with the latest version of co-op. Are you on Beta 30?

**Comment by Stiqu** [comment]
I wasn't at the time, after I updated it started working! Thanks for your help, and sorry for the confusion.
